"""Pin the exact decision_basis distribution of the shipped chaos artifact.

The submission ships `audit_log_chaos_seed42.json` as concrete evidence that
the unified registry distinguishes transient failures (retried + recovered)
from terminal logic errors (`stale_data`, which we deliberately never retry).

This file is not regenerated by the test suite — it is produced by the
demo (`scripts/demo.sh --chaos 0.15 --seed 42`) and checked in. The hazard
this test defends against is a future refactor that silently changes the
balance (e.g. inflating `successful_resolution` at the expense of
`tool_failure`) without the author noticing the shipped artifact is now
out-of-date relative to `SUBMISSION.md` / `DEMO.md`.

If this test fails, the correct response is almost always:
  1. rerun `./scripts/demo.sh --chaos 0.15 --seed 42`
  2. update the archived `audit_log_chaos_seed42.json`
  3. update the distribution numbers in `SUBMISSION.md` + `DEMO.md`
  4. update the counters below
All four must move together — the archive and the docs must never disagree.
"""
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARCHIVE = ROOT / "audit_log_chaos_seed42.json"


def _load() -> list[dict]:
    return json.loads(ARCHIVE.read_text(encoding="utf-8"))


def test_archive_exists_and_has_20_tickets() -> None:
    entries = _load()
    assert len(entries) == 20, f"expected 20 tickets in chaos archive, got {len(entries)}"


def test_outcome_distribution_is_pinned() -> None:
    entries = _load()
    outcomes = Counter(e["outcome"] for e in entries)
    assert outcomes == Counter(
        {"escalated": 10, "resolved": 9, "declined": 1}
    ), f"chaos outcome distribution drifted: {outcomes}"


def test_decision_basis_distribution_is_pinned() -> None:
    entries = _load()
    basis = Counter(e["decision_basis"] for e in entries)
    assert basis == Counter(
        {
            "successful_resolution": 8,
            "tool_failure": 6,
            "policy_guard": 2,
            "low_confidence": 2,
            "recovered_and_resolved": 1,
            "fraud_detected": 1,
        }
    ), f"chaos decision_basis distribution drifted: {basis}"


def test_recovery_attempted_count_is_pinned() -> None:
    entries = _load()
    attempted = sum(1 for e in entries if e.get("recovery_attempted"))
    assert attempted == 6, f"expected 6 tickets with recovery_attempted, got {attempted}"


def test_stale_data_is_never_recovered() -> None:
    """The registry classifies `stale_data` as non-retryable, so any failure
    with error='stale_data' must be recorded as recovered=False. Silent
    flipping of this flag would mask the exact behaviour the recovery
    demo is built around."""
    entries = _load()
    stale = [
        f
        for e in entries
        for f in e.get("failures") or []
        if f.get("error") == "stale_data"
    ]
    assert stale, "expected at least one stale_data failure in the chaos archive"
    assert all(not f["recovered"] for f in stale), (
        "a stale_data failure was marked recovered=True — that contradicts the "
        "registry policy in app/registry.py:_is_retryable"
    )
